### ISSUE TITLE
limit the IP address nessus

### ISSUE THREAD

**Issue by bibo318** [harshdhamaniya/nessuskeygen#1]
Requesting multiple keys will limit the IP address. How not to be limited? Or what is the limit?

Response from server: {"success":false,"statusCode":400"Your ip address xxx.xxx.xxx.xxx has already reached the limit of available evaluations",

**Comment by harshdhamaniya** [comment]
Nessus ban the IP after creating multiple keys. Please use a VPN or Proxy to bypass IP ban
