### ISSUE TITLE
In windows it is not working

### ISSUE THREAD

**Issue by GuruprasathL** [harshdhamaniya/nessuskeygen#3]
▒█▄░▒█ █▀▀ █▀▀ █▀▀ █░░█ █▀▀ 　 ▒█░▄▀ █▀▀ █░░█ █▀▀▀ █▀▀ █▀▀▄
▒█▒█▒█ █▀▀ ▀▀█ ▀▀█ █░░█ ▀▀█ 　 ▒█▀▄░ █▀▀ █▄▄█ █░▀█ █▀▀ █░░█
▒█░░▀█ ▀▀▀ ▀▀▀ ▀▀▀ ░▀▀▀ ▀▀▀ 　 ▒█░▒█ ▀▀▀ ▄▄▄█ ▀▀▀▀ ▀▀▀ ▀░░▀
==== Developed - Harsh Dhamaniya - Consultant ====
Welcome To Nessus Subscription Generator
1. Nessus Professional Key
2. Nessus Expert Email
Please Select Your Subscription: 1
Traceback (most recent call last):
  File "C:\Users\HP\nessuskeygen\nessuslicense.py", line 202, in <module>
    main()
  File "C:\Users\HP\nessuskeygen\nessuslicense.py", line 189, in main
    activation_code = generate_nessus_pro()
  File "C:\Users\HP\nessuskeygen\nessuslicense.py", line 58, in generate_nessus_pro
    response = requests.post('https://www.tenable.com/evaluations/api/v1/nessus-pro', json=data)
NameError: name 'requests' is not defined

**Comment by harshdhamaniya** [comment]
Please install the requests python module.
pip install requests

**Comment by GuruprasathL** [comment]
After installing requests it shows the same error
